# Build and Push cisco-fmc-tool

trigger: none
pr:
 branches:
   include:
     - master
 paths:
   include:
     - Dockerfile
     - .dockerignore
   
pool:
  name: 'infrastructure-agents'

steps:
- task: Docker@2
  displayName: Push Harbor Image
  inputs:
    containerRegistry: ''
    repository: 'infrastructure/fmc'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
